"""Alembic environment. Runs migrations against DATABASE_URL_SYNC.

Migrations are explicit SQL (not autogenerated), so this environment has no
dependency on service code — the migration runner only needs alembic + a DB URL.
"""

from __future__ import annotations

import os

from alembic import context
from sqlalchemy import engine_from_config, pool

config = context.config

db_url = os.environ.get(
    "DATABASE_URL_SYNC", "postgresql+psycopg://aios:aios@localhost:5432/aios"
)
config.set_main_option("sqlalchemy.url", db_url)


def run_migrations_offline() -> None:
    context.configure(url=db_url, literal_binds=True, dialect_opts={"paramstyle": "named"})
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
